### ISSUE TITLE
Generating Generate Random Password in Laravel 10

### ISSUE THREAD

**Issue by rajoyish** [LaravelDaily/Laravel-Livewire-Orders#1]
I got the following error while implementing Generate Random Password method:

```php
App\Http\Middleware\RedirectIfAuthenticated::handle(): Return value must be of type Symfony\Component\HttpFoundation\Response, null returned
```

P.S. I am using Laravel 10 for this course.

**Comment by PovilasKorop** [comment]
@rajoyish we had used Laravel 9 for this course, so I'm not sure if it's a relevant issue, to be honest

**Comment by krekas** [comment]
With Livewire v2.11.3 it was fixed. If you want to check, pr can be found here https://github.com/livewire/livewire/pull/5561
